
from pptx import Presentation
from pptx.util import Inches

def create_presentation():
    # Create a new presentation
    prs = Presentation()

    # Access the slide master to modify footers
    for slide_layout in prs.slide_masters:
        if slide_layout.footer is not None:
            slide_layout.footer.text = 'Generated by safe AI locally'

    # Slide 1: Title Slide
    title_slide_layout = prs.slide_masters[0]  # Assuming first layout is title slide
    slide = prs.slides.add_slide(title_slide_layout, None)  # Add title slide

    title = slide.shapes.title
    subtitle = slide.placeholders[1]

    title.text = "China"
    subtitle.text = "A Glimpse into the World's Oldest Civilization"

    # Add your name and date (placeholders)
    notes_slide = slide.notes_slide

    # Save the presentation
    prs.save("china_presentation.pptx")

# Execute the function when script runs
if __name__ == "__main__":
    create_presentation()
