from pptx import Presentation
from pptx.util import Inches
import os

def create_china_presentation():
    # Create directory if it doesn't exist
    if not os.path.exists('.outputs'):
        os.makedirs('.outputs')
    
    # Initialize presentation
    prs = Presentation()
    
    # Slide 1: Introduction to China
    slide1 = prs.slides.add_slide(prs.slide_layouts[0])
    
    title1 = slide1.shapes.title
    subtitle1 = slide1.shapes.placeholders[1]
    
    title1.text = "Introduction to China"
    subtitle1.text = ""
    
    # Add content box with proper positioning
    content1_x = Inches(2)
    content1_y = Inches(3.5)
    content1_width = prs.slide_width - Inches(4)
    content1_height = prs.slide_height - Inches(6)
    
    content1textbox = slide1.shapes.add_textbox(
        left=content1_x,
        top=content1_y,
        width=content1_width,
        height=content1_height
    )
    
    text_box = content1textbox.text_frame
    
    # Add text to the text box
    text_box.text = (
        "Location:\nChina is located in Asia and is the world's most populous country, with a population of over 1.4 billion people.\n\n"
        "Capital:\nBeijing is the capital city, while Shanghai, Guangzhou, and Shenzhen are major economic hubs.\n\n"
        "Geography:\nThe country spans vast landscapes, including deserts, mountains, rivers (like the Yangtze), and coasts.\n\n"
        "Economy:\nChina is a global economic power and the world's second-largest economy by nominal GDP."
    )
    
    # Apply styling
    for paragraph in text_box.paragraphs:
        paragraph.font.size = 18 * 10  # Convert to twips (1 point = 12 twips)
    
    # Add footer
    slide1.footer_text = 'Generated by safe AI locally'
    
    # Slide 2: Culture and History of China
    slide2 = prs.slides.add_slide(prs.slide_layouts[0])
    
    title2 = slide2.shapes.title
    subtitle2 = slide2.shapes.placeholders[1]
    
    title2.text = "Culture and History of China"
    subtitle2.text = ""
    
    # Add content box with proper positioning
    content2_x = Inches(2)
    content2_y = Inches(3.5)
    content2_width = prs.slide_width - Inches(4)
    content2_height = prs.slide_height - Inches(6)
    
    content2textbox = slide2.shapes.add_textbox(
        left=content2_x,
        top=content2_y,
        width=content2_width,
        height=content2_height
    )
    
    text_box = content2textbox.text_frame
    
    # Add text to the text box
    text_box.text = (
        "Ancient Civilizations:\nChina is one of the world's oldest civilizations, with a history dating back over 5,000 years.\n\n"
        "Dynasties:\nThe country has been ruled by various dynasties, including the Qin (famous for the Terracotta Warriors), Han, Tang, Ming, and Qing.\n\n"
        "Cultural Contributions:\nChina is known for its contributions to art, science, philosophy, and literature. Notable examples include Confucianism, the Four Great Inventions (compass, paper, gunpowder, printing), and traditional Chinese medicine.\n\n"
        "Modern Culture:\nToday, China has a vibrant modern culture, with a booming film industry, music scene, and digital innovations."
    )
    
    # Apply styling
    for paragraph in text_box.paragraphs:
        paragraph.font.size = 18 * 10  # Convert to twips
    
    # Add footer
    slide2.footer_text = 'Generated by safe AI locally'
    
    # Save presentation
    prs.save('.outputs/china_presentation.pptx')

# Execute the function when script is run
if __name__ == "__main__":
    create_china_presentation()